### ISSUE TITLE
Make sure you have both data and texture files in the same directory for

### ISSUE THREAD

**Issue by ayqy** [pavle-goloskokovic/texture-unpacker#4]
Nice project. 2 problems here:
1. feature request: absolute file path support
2. doc request: file path example, should I pass `imgs/packed.png` or `imgs` or `imgs/packed.json` or correct `imgs/packed`

**Comment by pavle-goloskokovic** [comment]
Thanks!

1. Absolute path support added. (https://github.com/pavle-goloskokovic/texture-unpacker/commit/9ab848fd345963b82e00a2ceeef2f41e308396b8)
2. You can find usage examples at the bottom of the [README file](https://github.com/pavle-goloskokovic/texture-unpacker/blob/master/README.md).
