### ISSUE TITLE
[feature request] Use different foldername if file by same name exists

### ISSUE THREAD

**Issue by SuggonM** [pavle-goloskokovic/texture-unpacker#6]
Hello! The codebase has been extreme helpful lately so I'm here again, this time with a minor feature request.

As the title says, the script should preferably create folder with a different name if a file by the same name already exists in the current directory. This is usually an unwanted case of collision where the script mistakens the extension-less main asset having the same name as its texture+atlas for a directory, and begins unpacking there, leading to some... unpleasant runtime errors. I'd very much appreciate if the script could somehow distinguish between a file and a folder, and act accordingly &mdash; maybe by appending `_unpacked` to the new foldername if the asset file exists.

For simplicity, the function that creates folder is in https://github.com/pavle-goloskokovic/texture-unpacker/blob/master/unpacker.ts#L346

**Comment by pavle-goloskokovic** [comment]
Hi @SuggonM, thanks for the suggestion!

Can you give me an example of the unpacker command you are using and folder structure that is causing you issues.

I want to understand better so I can come up with the best solution.

Thanks!

**Comment by SuggonM** [comment]
Sure, I do have an example for that!

Considering the directory in this repository https://github.com/SuggonM/gt-scripts/tree/main/worldmap/chapter_1.
1. `chapter_1` is the asset (not a directory)
2. `chapter_1.png` is the obtained texture
3. `chapter_1.json` is the obtained atlas

When simply running command `npm run unpack "<absolute_path>/worldmap/chapter_1/chapter_1.png" json` (which is what [extract.bat](https://github.com/SuggonM/gt-scripts/blob/main/worldmap/extract.bat#L37) does), the console throws this error:

```
'easy_forest_1_1.png' error: [Error: <path>\chapter_1\chapter_1\easy_forest_1_1.png: unable to open for write
<path>\chapter_1\chapter_1\easy_forest_1_1.png: unable to open for write
windows error: The system cannot find the file specified.
```

The likely cause being that it's trying to unpack into `chapter_1` which is a file rather than a directory that can hold files.

I'm aware the asset file itself could simply be renamed to something else, but that'd probably only be a bandaid solution. And also it'd be much better to handle such edge-cases from within the script itself.

**Comment by pavle-goloskokovic** [comment]
Thanks for the detailed reproduction steps!

I had the idea of improving how arguments are passed and have more configurable options, such as output path which would resolve your issue.

It is not a trivial task and will take some time to implement.

Until then, I suggest you fork the repo or change your local copy which you use for unpacking by appending `_unpacked` to the output path here: https://github.com/pavle-goloskokovic/texture-unpacker/blob/95af8e7dfe92e0ffb36246ff463825c6f8c5c3f3/unpacker.ts#L353

to be:

```javascript
const outPath = appendTextureExt(join(filePath + '_unpacked', spriteName));
```

**Comment by pavle-goloskokovic** [comment]
Ok, I was able to implement custom arguments parsing, so it should be fairly simple to change the output path and resolve your issue.

Take a look at the updated [README.md](https://github.com/pavle-goloskokovic/texture-unpacker/blob/ad8d348fdebd5bf107159813c6681f91be5685d9/README.md) file, specifically usage and example sections.

Thanks for reporting issues and helping improve this tool!
