### ISSUE TITLE
Issue with unpacking a sprite sheet with directories

### ISSUE THREAD

**Issue by VoltageMiner** [pavle-goloskokovic/texture-unpacker#7]
I'm trying to unpack a sprite sheet with a `.plist` data file, but I'm running into an issue where directories defined in the data file are not being created. This causes Windows 10 to spit out errors such as  `unable to open for write` and `windows error: The system cannot find the file specified.`. This wasn't an issue in an older version of this program that I previously used.

For example, if `<key>test_folder/image_1.png</key>` is defined in the data file, the `test_folder` directory isn't created. The other sprites outputted without a directory were created successfully, though.

**Comment by pavle-goloskokovic** [comment]
The issue was resolved with https://github.com/pavle-goloskokovic/texture-unpacker/commit/739db0b0d95644bd4df3041e23c0b4864874ff52.

Make sure to pull the latest version before using it again.

Thanks for reporting issues and helping improve this tool!
